apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: kyrilltest3-cronjob:batch/CronJob:scheduledtask-test/autobookingconfirmer-live-293ku-20ef1
    comment: ""
    documentation: https://traveltrex.atlassian.net/wiki/spaces/ITSoftware/pages/28051031/AutoBookingConfirmer
    environment: live
    image: registry.k8s.traveltrex.local/schedtask-dotnet-linux
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"CronJob","metadata":{"annotations":{"comment":"10.2.2025, 17:37:18 - Francesco Riggio: Noch nicht nachts auszuführen","documentation":"https://traveltrex.atlassian.net/wiki/spaces/ITSoftware/pages/149029240/AgenturDatenanlageKorrekturen","forceCompleteRequest":"0001-01-01T00:00:00.0000000","image":"registry.k8s.traveltrex.local/schedtask-powershell","lastchangeoperation":"Edit","lastchangetime":"2025-02-10T17:34:11.520+01:00","lastchangeuser":"Francesco Riggio","logging":"","nagiosLabels":"TEAMVK","tag":"1.0.17","template":"schedtask-powershell"},"labels":{"argocd.argoproj.io/instance":"kubertasks-cronjobs","groupName":"AgenturDatenanlageKorrekturen"},"name":"agenturdatenanlagekorrekturen-w7w6l","namespace":"scheduledtask"},"spec":{"concurrencyPolicy":"Forbid","failedJobsHistoryLimit":1,"jobTemplate":{"metadata":{"labels":{"groupName":"AgenturDatenanlageKorrekturen"}},"spec":{"activeDeadlineSeconds":120,"backoffLimit":0,"template":{"metadata":{"labels":{"groupName":"AgenturDatenanlageKorrekturen"}},"spec":{"containers":[{"env":[{"name":"SCRIPT","value":"AgenturDatenanlageKorrekturen.ps1 live"},{"name":"DIRECTORY","value":"AgenturDatenanlageKorrekturen"}],"image":"registry.k8s.traveltrex.local/schedtask-powershell:1.0.17","imagePullPolicy":"IfNotPresent","name":"powershell","resources":{"limits":{"cpu":"190m","memory":"260Mi"},"requests":{"cpu":"100m","memory":"250Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/mnt/scheduledtask","name":"pvc-taskplaner-tools"}]}],"dnsPolicy":"ClusterFirst","nodeSelector":{"kubernetes.io/os":"linux"},"restartPolicy":"Never","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"pvc-taskplaner-tools","persistentVolumeClaim":{"claimName":"pvc-taskplaner-tools"}}]}}}},"schedule":"0 0 * * *","startingDeadlineSeconds":21600,"successfulJobsHistoryLimit":1,"suspend":true,"timeZone":"Europe/Berlin"}}
    lastchangeoperation: Edit
    lastchangetime: "2026-01-02T09:01:10.992+01:00"
    lastchangeuser: Christian Weirich
    logging: http://logstash-intern:9292/index.html#/dashboard/elasticsearch/AutoBookingConfirmer
    nagiosLabels: TEAMVK
    tag: 8.0-3.0.3
    template: schedtask-dotnet-linux
  creationTimestamp: "2026-01-07T15:36:16Z"
  generation: 1
  labels:
    groupName: AutoBookingConfirmer-Live
  name: autobookingconfirmer-live-293ku-20ef1
  namespace: scheduledtask-test
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        groupName: AutoBookingConfirmer-Live
    spec:
      activeDeadlineSeconds: 300
      backoffLimit: 0
      template:
        metadata:
          labels:
            groupName: AutoBookingConfirmer-Live
        spec:
          containers:
          - env:
            - name: TASK
              value: ./net8/AutoBookingConfirmer.dll umgebung=Live
            - name: TASKDIR
              value: AutoBookingConfirmer
            image: registry.k8s.traveltrex.local/schedtask-dotnet-linux:8.0-3.0.3
            imagePullPolicy: IfNotPresent
            name: schedtask-dotnet-linux
            resources:
              limits:
                cpu: 200m
                memory: 200Mi
              requests:
                cpu: 150m
                memory: 150Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /mnt/scheduledtask
              name: taskplaner-tools
            - mountPath: /mnt/scheduledtask/L
              name: scheduledtask-l
          dnsPolicy: ClusterFirst
          nodeSelector:
            kubernetes.io/os: linux
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - name: taskplaner-tools
            persistentVolumeClaim:
              claimName: pvc-taskplaner-tools
          - name: scheduledtask-l
            persistentVolumeClaim:
              claimName: pvc-scheduledtask-l
  schedule: '* 1-23 * * *'
  startingDeadlineSeconds: 21600
  successfulJobsHistoryLimit: 1
  suspend: true
  timeZone: Europe/Berlin
---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: kyrilltest3-cronjob:batch/CronJob:scheduledtask-test/autobookingconfirmer-live-6mop5-1eeb3
    comment: ""
    documentation: https://traveltrex.atlassian.net/wiki/spaces/ITSoftware/pages/28051031/AutoBookingConfirmer
    environment: live
    image: registry.k8s.traveltrex.local/schedtask-dotnet-linux
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"CronJob","metadata":{"annotations":{"comment":"10.2.2025, 17:37:18 - Francesco Riggio: Noch nicht nachts auszuführen","documentation":"https://traveltrex.atlassian.net/wiki/spaces/ITSoftware/pages/149029240/AgenturDatenanlageKorrekturen","forceCompleteRequest":"0001-01-01T00:00:00.0000000","image":"registry.k8s.traveltrex.local/schedtask-powershell","lastchangeoperation":"Edit","lastchangetime":"2025-02-10T17:34:11.520+01:00","lastchangeuser":"Francesco Riggio","logging":"","nagiosLabels":"TEAMVK","tag":"1.0.17","template":"schedtask-powershell"},"labels":{"argocd.argoproj.io/instance":"kubertasks-cronjobs","groupName":"AgenturDatenanlageKorrekturen"},"name":"agenturdatenanlagekorrekturen-w7w6l","namespace":"scheduledtask"},"spec":{"concurrencyPolicy":"Forbid","failedJobsHistoryLimit":1,"jobTemplate":{"metadata":{"labels":{"groupName":"AgenturDatenanlageKorrekturen"}},"spec":{"activeDeadlineSeconds":120,"backoffLimit":0,"template":{"metadata":{"labels":{"groupName":"AgenturDatenanlageKorrekturen"}},"spec":{"containers":[{"env":[{"name":"SCRIPT","value":"AgenturDatenanlageKorrekturen.ps1 live"},{"name":"DIRECTORY","value":"AgenturDatenanlageKorrekturen"}],"image":"registry.k8s.traveltrex.local/schedtask-powershell:1.0.17","imagePullPolicy":"IfNotPresent","name":"powershell","resources":{"limits":{"cpu":"190m","memory":"260Mi"},"requests":{"cpu":"100m","memory":"250Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/mnt/scheduledtask","name":"pvc-taskplaner-tools"}]}],"dnsPolicy":"ClusterFirst","nodeSelector":{"kubernetes.io/os":"linux"},"restartPolicy":"Never","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"pvc-taskplaner-tools","persistentVolumeClaim":{"claimName":"pvc-taskplaner-tools"}}]}}}},"schedule":"0 0 * * *","startingDeadlineSeconds":21600,"successfulJobsHistoryLimit":1,"suspend":true,"timeZone":"Europe/Berlin"}}
    lastchangeoperation: Edit
    lastchangetime: "2026-01-02T09:01:10.992+01:00"
    lastchangeuser: Christian Weirich
    logging: http://logstash-intern:9292/index.html#/dashboard/elasticsearch/AutoBookingConfirmer
    nagiosLabels: TEAMVK
    tag: 8.0-3.0.3
    template: schedtask-dotnet-linux
  creationTimestamp: "2026-01-07T15:36:16Z"
  generation: 1
  labels:
    groupName: AutoBookingConfirmer-Live
  name: autobookingconfirmer-live-6mop5-1eeb3
  namespace: scheduledtask-test
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        groupName: AutoBookingConfirmer-Live
    spec:
      activeDeadlineSeconds: 300
      backoffLimit: 0
      template:
        metadata:
          labels:
            groupName: AutoBookingConfirmer-Live
        spec:
          containers:
          - env:
            - name: TASK
              value: ./net8/AutoBookingConfirmer.dll umgebung=Live
            - name: TASKDIR
              value: AutoBookingConfirmer
            image: registry.k8s.traveltrex.local/schedtask-dotnet-linux:8.0-3.0.3
            imagePullPolicy: IfNotPresent
            name: schedtask-dotnet-linux
            resources:
              limits:
                cpu: 200m
                memory: 200Mi
              requests:
                cpu: 150m
                memory: 150Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /mnt/scheduledtask
              name: taskplaner-tools
            - mountPath: /mnt/scheduledtask/L
              name: scheduledtask-l
          dnsPolicy: ClusterFirst
          nodeSelector:
            kubernetes.io/os: linux
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - name: taskplaner-tools
            persistentVolumeClaim:
              claimName: pvc-taskplaner-tools
          - name: scheduledtask-l
            persistentVolumeClaim:
              claimName: pvc-scheduledtask-l
  schedule: 30/1 0 * * *
  startingDeadlineSeconds: 21600
  successfulJobsHistoryLimit: 1
  suspend: true

  timeZone: Europe/Berlin

