apiVersion: batch/v1  
kind: CronJob  
metadata:  
  name: kyrilltest2-bskap
  labels:  
    groupName: KyrillTest2
  namespace: scheduledtask-test
spec:  
  schedule: "0 3 * * *"
  suspend: true
  jobTemplate:  
    spec:
      template:
        metadata:
          labels:
            groupName: KyrillTest2
        spec:  
          containers:  
          - name: backup  
            image: busybox:1.35  
            command:  
            - /bin/sh  
            - -c  
            - "echo 'Running backup task 2' && sleep 30"  
          restartPolicy: OnFailure